"""empty message

Revision ID: 06f64b5ad85f
Revises: 2ac4a3a3b14e
Create Date: 2023-02-13 00:57:01.361624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f64b5ad85f'
down_revision = '2ac4a3a3b14e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set', sa.Column('match_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'set', 'match', ['match_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'set', type_='foreignkey')
    op.drop_column('set', 'match_id')
    # ### end Alembic commands ###
