"""empty message

Revision ID: 2ac4a3a3b14e
Revises: d085be55e81e
Create Date: 2023-02-13 00:51:50.865238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac4a3a3b14e'
down_revision = 'd085be55e81e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('player_a_id', sa.Integer(), nullable=False))
    op.add_column('match', sa.Column('player_b_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'match', 'player', ['player_b_id'], ['id'])
    op.create_foreign_key(None, 'match', 'player', ['player_a_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_column('match', 'player_b_id')
    op.drop_column('match', 'player_a_id')
    # ### end Alembic commands ###
