"""empty message

Revision ID: 3d586b3ad76a
Revises: 06f64b5ad85f
Create Date: 2023-02-13 01:00:08.789302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d586b3ad76a'
down_revision = '06f64b5ad85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('set_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'game', 'set', ['set_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'set_id')
    # ### end Alembic commands ###
