"""empty message

Revision ID: 3e8b08c889e4
Revises: ae7cc916ed01
Create Date: 2023-02-16 16:51:47.144868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8b08c889e4'
down_revision = 'ae7cc916ed01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat', sa.Column('set_won', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stat', 'set_won')
    # ### end Alembic commands ###
