"""empty message

Revision ID: 5429d46b7e82
Revises: 919436382503
Create Date: 2023-02-13 00:38:03.180489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5429d46b7e82'
down_revision = '919436382503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aces', sa.Integer(), nullable=True),
    sa.Column('winners', sa.Integer(), nullable=True),
    sa.Column('double_faults', sa.Integer(), nullable=True),
    sa.Column('unforced_errors', sa.Integer(), nullable=True),
    sa.Column('forced_errors', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stat')
    # ### end Alembic commands ###
