"""empty message

Revision ID: 66db0f8893ee
Revises: df1ba5258246
Create Date: 2023-02-13 00:32:22.803152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66db0f8893ee'
down_revision = 'df1ba5258246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('set',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=True),
    sa.Column('player_a_games_won', sa.Integer(), nullable=True),
    sa.Column('player_b_games_won', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set')
    # ### end Alembic commands ###
