"""empty message

Revision ID: 724b219efbe4
Revises: d52f8f8757c1
Create Date: 2023-02-16 16:30:53.735546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724b219efbe4'
down_revision = 'd52f8f8757c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set', sa.Column('set_winner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('set', 'set_winner')
    # ### end Alembic commands ###
