"""adds All  models

Revision ID: 93064f157275
Revises: 
Create Date: 2023-02-12 18:21:06.778519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93064f157275'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('no_of_sets', sa.Integer(), nullable=True),
    sa.Column('no_of_gamesperset', sa.Integer(), nullable=True),
    sa.Column('match_date', sa.DateTime(), nullable=True),
    sa.Column('match_name', sa.String(), nullable=True),
    sa.Column('player_a_id', sa.Integer(), nullable=False),
    sa.Column('player_b_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_a_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['player_b_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=False),
    sa.Column('serve_style', sa.String(), nullable=False),
    sa.Column('utr', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_number', sa.Integer(), nullable=True),
    sa.Column('player_a_score', sa.Integer(), nullable=True),
    sa.Column('player_b_score', sa.Integer(), nullable=True),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('set',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=True),
    sa.Column('player_a_gmaes_won', sa.Integer(), nullable=True),
    sa.Column('player_b_gmaes_won', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_a_id', sa.Integer(), nullable=False),
    sa.Column('player_b_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['player_a_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['player_b_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aces', sa.Integer(), nullable=True),
    sa.Column('winners', sa.Integer(), nullable=True),
    sa.Column('double_faults', sa.Integer(), nullable=True),
    sa.Column('unforced_errors', sa.Integer(), nullable=True),
    sa.Column('forced_errors', sa.Integer(), nullable=True),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('player_a_id', sa.Integer(), nullable=False),
    sa.Column('player_b_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_a_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['player_b_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stat')
    op.drop_table('set')
    op.drop_table('game')
    op.drop_table('user')
    op.drop_table('player')
    op.drop_table('match')
    # ### end Alembic commands ###
