"""empty message

Revision ID: ae7cc916ed01
Revises: 724b219efbe4
Create Date: 2023-02-16 16:40:46.252088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7cc916ed01'
down_revision = '724b219efbe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('game_winner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'game_winner')
    # ### end Alembic commands ###
