"""empty message

Revision ID: d085be55e81e
Revises: d1af0259bbb0
Create Date: 2023-02-13 00:45:51.317013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd085be55e81e'
down_revision = 'd1af0259bbb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'match', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_column('match', 'user_id')
    # ### end Alembic commands ###
