"""empty message

Revision ID: d1af0259bbb0
Revises: 5429d46b7e82
Create Date: 2023-02-13 00:43:53.748610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1af0259bbb0'
down_revision = '5429d46b7e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'player', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_column('player', 'user_id')
    # ### end Alembic commands ###
