"""empty message

Revision ID: d52f8f8757c1
Revises: 3bd05bf5ca3f
Create Date: 2023-02-16 16:12:19.059674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd52f8f8757c1'
down_revision = '3bd05bf5ca3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('match_winner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'match_winner')
    # ### end Alembic commands ###
