"""empty message

Revision ID: df1ba5258246
Revises: 230a0c79f305
Create Date: 2023-02-13 00:29:22.314313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1ba5258246'
down_revision = '230a0c79f305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('no_of_sets', sa.Integer(), nullable=True),
    sa.Column('no_of_gamesperset', sa.Integer(), nullable=True),
    sa.Column('match_date', sa.DateTime(), nullable=True),
    sa.Column('match_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###
