"""empty message

Revision ID: e24007641b8b
Revises: 3e8b08c889e4
Create Date: 2023-02-16 17:23:13.798022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24007641b8b'
down_revision = '3e8b08c889e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('player_a_sets_won', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('player_b_sets_won', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'player_b_sets_won')
    op.drop_column('match', 'player_a_sets_won')
    # ### end Alembic commands ###
