"""empty message

Revision ID: fa5ffc4cc8c8
Revises: e24007641b8b
Create Date: 2023-02-18 17:01:04.608239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5ffc4cc8c8'
down_revision = 'e24007641b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('game_done', sa.Boolean(), nullable=True))
    op.add_column('match', sa.Column('match_done', sa.Boolean(), nullable=True))
    op.add_column('set', sa.Column('set_done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('set', 'set_done')
    op.drop_column('match', 'match_done')
    op.drop_column('game', 'game_done')
    # ### end Alembic commands ###
